### PR TITLE
fix(`participation`): proper auction status checks in `msgParticipate`

### LINKED ISSUE #696: Check `Status` field of auction in `MsgParticpate`
Currently we use the `ShouldAuctionStarted()` function to check if the auction is started in `MsgParticipate`.

We should instead use the `GetStatus()` method and evaluate based on the Auction Status field.

### PR DESCRIPTION
**Pull request by giunatale**
Closes #696

### CODE REVIEW

File: x/participation/keeper/msg_participate_test.go [hunk 1]
```diff
@@ -37,14 +37,22 @@ func Test_msgServer_Participate(t *testing.T) {
 	// initialize auction
 	tk.Mint(sdkCtx, auctioneer, sdk.NewCoins(sellingCoin1))
 	auctionID1 := tk.CreateFixedPriceAuction(sdkCtx, r, auctioneer, sellingCoin1, startTime, endTime)
-	// initialize auction with edge case start time
+	// initialize auction with edge case start time (forcefully set to status standby)
```
Comment (lubtd) [inline x/participation/keeper/msg_participate_test.go:40]: Just a feedback that I should have already given before. I would suggest using more explicit names depending on the test case for the variables. Using numbers makes the tests hard to read
Example
`auctionID1` -> `auctionRegistrationPeriod`
`auctionID3` -> `auctionStarted`

**Review by aljo242 — APPROVED** [review]

**Review by lubtd — APPROVED** [review]
